--------------------------------------------------------
--  File created - 星期一-六月-21-2021   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Sequence SEQ_C_ID
--------------------------------------------------------

   CREATE SEQUENCE  "SCOTT"."SEQ_C_ID"  MINVALUE 0 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_I_ID
--------------------------------------------------------

   CREATE SEQUENCE  "SCOTT"."SEQ_I_ID"  MINVALUE 0 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 121 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_S_ID
--------------------------------------------------------

   CREATE SEQUENCE  "SCOTT"."SEQ_S_ID"  MINVALUE 0 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 161 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Table ACCOUNT
--------------------------------------------------------

  CREATE TABLE "SCOTT"."ACCOUNT" 
   (	"USER_ID" VARCHAR2(20), 
	"PASSWORD" VARCHAR2(20), 
	"IDENTITY" CHAR(1)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TEACHINGMANAGER" ;
--------------------------------------------------------
--  DDL for Table COURSE
--------------------------------------------------------

  CREATE TABLE "SCOTT"."COURSE" 
   (	"ID" VARCHAR2(10), 
	"TITLE" VARCHAR2(20), 
	"INS_ID" VARCHAR2(10), 
	"DEPT_NAME" VARCHAR2(10), 
	"HOURS" NUMBER(2,0), 
	"CREDITS" NUMBER(1,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TEACHINGMANAGER" ;
--------------------------------------------------------
--  DDL for Table DEPARTMENT
--------------------------------------------------------

  CREATE TABLE "SCOTT"."DEPARTMENT" 
   (	"NAME" VARCHAR2(10), 
	"BUILDING" VARCHAR2(20), 
	"DESCRIPE" CLOB
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TEACHINGMANAGER" 
 LOB ("DESCRIPE") STORE AS BASICFILE (
  TABLESPACE "TEACHINGMANAGER" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
--------------------------------------------------------
--  DDL for Table ELECT
--------------------------------------------------------

  CREATE TABLE "SCOTT"."ELECT" 
   (	"S_ID" VARCHAR2(10), 
	"C_ID" VARCHAR2(10), 
	"COMPLETED" CHAR(1)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TEACHINGMANAGER" ;
--------------------------------------------------------
--  DDL for Table INSTRUCTOR
--------------------------------------------------------

  CREATE TABLE "SCOTT"."INSTRUCTOR" 
   (	"ID" VARCHAR2(10), 
	"NAME" VARCHAR2(20), 
	"SEX" CHAR(1), 
	"DEPT_NAME" VARCHAR2(20), 
	"POSITION" CHAR(1)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TEACHINGMANAGER" ;
--------------------------------------------------------
--  DDL for Table LOG
--------------------------------------------------------

  CREATE TABLE "SCOTT"."LOG" 
   (	"CREATER" VARCHAR2(20), 
	"RELATED" VARCHAR2(20), 
	"TIME" DATE DEFAULT sysdate
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TEACHINGMANAGER" ;
--------------------------------------------------------
--  DDL for Table STUDENT
--------------------------------------------------------

  CREATE TABLE "SCOTT"."STUDENT" 
   (	"ID" VARCHAR2(10), 
	"NAME" VARCHAR2(20), 
	"SEX" CHAR(1), 
	"DEPT_NAME" VARCHAR2(20), 
	"TOL_CRED" NUMBER(5,0) DEFAULT 0
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TEACHINGMANAGER" ;
--------------------------------------------------------
--  Constraints for Table ACCOUNT
--------------------------------------------------------

  ALTER TABLE "SCOTT"."ACCOUNT" MODIFY ("PASSWORD" NOT NULL ENABLE);
 
  ALTER TABLE "SCOTT"."ACCOUNT" ADD PRIMARY KEY ("USER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TEACHINGMANAGER"  ENABLE;
 
  ALTER TABLE "SCOTT"."ACCOUNT" MODIFY ("IDENTITY" NOT NULL ENABLE);
 
  ALTER TABLE "SCOTT"."ACCOUNT" ADD CHECK ("IDENTITY"='M' OR "IDENTITY"='S' OR "IDENTITY"='I') ENABLE;
--------------------------------------------------------
--  Constraints for Table COURSE
--------------------------------------------------------

  ALTER TABLE "SCOTT"."COURSE" MODIFY ("INS_ID" NOT NULL ENABLE);
 
  ALTER TABLE "SCOTT"."COURSE" MODIFY ("DEPT_NAME" NOT NULL ENABLE);
 
  ALTER TABLE "SCOTT"."COURSE" MODIFY ("HOURS" NOT NULL ENABLE);
 
  ALTER TABLE "SCOTT"."COURSE" MODIFY ("CREDITS" NOT NULL ENABLE);
 
  ALTER TABLE "SCOTT"."COURSE" ADD CHECK (HOURS>0) ENABLE;
 
  ALTER TABLE "SCOTT"."COURSE" ADD CHECK (CREDITS>0) ENABLE;
 
  ALTER TABLE "SCOTT"."COURSE" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TEACHINGMANAGER"  ENABLE;
 
  ALTER TABLE "SCOTT"."COURSE" ADD UNIQUE ("TITLE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TEACHINGMANAGER"  ENABLE;
 
  ALTER TABLE "SCOTT"."COURSE" MODIFY ("TITLE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table DEPARTMENT
--------------------------------------------------------

  ALTER TABLE "SCOTT"."DEPARTMENT" MODIFY ("BUILDING" NOT NULL ENABLE);
 
  ALTER TABLE "SCOTT"."DEPARTMENT" ADD PRIMARY KEY ("NAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TEACHINGMANAGER"  ENABLE;
--------------------------------------------------------
--  Constraints for Table ELECT
--------------------------------------------------------

  ALTER TABLE "SCOTT"."ELECT" ADD CHECK (COMPLETED IN ('Y','N')) ENABLE;
 
  ALTER TABLE "SCOTT"."ELECT" ADD UNIQUE ("S_ID", "C_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table INSTRUCTOR
--------------------------------------------------------

  ALTER TABLE "SCOTT"."INSTRUCTOR" MODIFY ("NAME" NOT NULL ENABLE);
 
  ALTER TABLE "SCOTT"."INSTRUCTOR" MODIFY ("SEX" NOT NULL ENABLE);
 
  ALTER TABLE "SCOTT"."INSTRUCTOR" MODIFY ("DEPT_NAME" NOT NULL ENABLE);
 
  ALTER TABLE "SCOTT"."INSTRUCTOR" MODIFY ("POSITION" NOT NULL ENABLE);
 
  ALTER TABLE "SCOTT"."INSTRUCTOR" ADD CHECK (SEX IN ('F', 'M')) ENABLE;
 
  ALTER TABLE "SCOTT"."INSTRUCTOR" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TEACHINGMANAGER"  ENABLE;
 
  ALTER TABLE "SCOTT"."INSTRUCTOR" ADD CHECK (POSITION IN ('A','B','C')) ENABLE;
--------------------------------------------------------
--  Constraints for Table LOG
--------------------------------------------------------

  ALTER TABLE "SCOTT"."LOG" MODIFY ("CREATER" NOT NULL ENABLE);
 
  ALTER TABLE "SCOTT"."LOG" MODIFY ("RELATED" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table STUDENT
--------------------------------------------------------

  ALTER TABLE "SCOTT"."STUDENT" MODIFY ("NAME" NOT NULL ENABLE);
 
  ALTER TABLE "SCOTT"."STUDENT" MODIFY ("SEX" NOT NULL ENABLE);
 
  ALTER TABLE "SCOTT"."STUDENT" MODIFY ("DEPT_NAME" NOT NULL ENABLE);
 
  ALTER TABLE "SCOTT"."STUDENT" ADD CHECK (TOL_CRED >= 0) ENABLE;
 
  ALTER TABLE "SCOTT"."STUDENT" ADD CHECK (SEX IN ('F', 'M')) ENABLE;
 
  ALTER TABLE "SCOTT"."STUDENT" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TEACHINGMANAGER"  ENABLE;
--------------------------------------------------------
--  DDL for Index SYS_C0011140
--------------------------------------------------------

  CREATE UNIQUE INDEX "SCOTT"."SYS_C0011140" ON "SCOTT"."ACCOUNT" ("USER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TEACHINGMANAGER" ;
--------------------------------------------------------
--  DDL for Index SYS_C0011121
--------------------------------------------------------

  CREATE UNIQUE INDEX "SCOTT"."SYS_C0011121" ON "SCOTT"."COURSE" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TEACHINGMANAGER" ;
--------------------------------------------------------
--  DDL for Index SYS_C0011122
--------------------------------------------------------

  CREATE UNIQUE INDEX "SCOTT"."SYS_C0011122" ON "SCOTT"."COURSE" ("TITLE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TEACHINGMANAGER" ;
--------------------------------------------------------
--  DDL for Index SYS_C0011106
--------------------------------------------------------

  CREATE UNIQUE INDEX "SCOTT"."SYS_C0011106" ON "SCOTT"."DEPARTMENT" ("NAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TEACHINGMANAGER" ;
--------------------------------------------------------
--  DDL for Index SYS_C0011423
--------------------------------------------------------

  CREATE UNIQUE INDEX "SCOTT"."SYS_C0011423" ON "SCOTT"."ELECT" ("S_ID", "C_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C0011114
--------------------------------------------------------

  CREATE UNIQUE INDEX "SCOTT"."SYS_C0011114" ON "SCOTT"."INSTRUCTOR" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TEACHINGMANAGER" ;
--------------------------------------------------------
--  DDL for Index SYS_C0011104
--------------------------------------------------------

  CREATE UNIQUE INDEX "SCOTT"."SYS_C0011104" ON "SCOTT"."STUDENT" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TEACHINGMANAGER" ;

--------------------------------------------------------
--  Ref Constraints for Table COURSE
--------------------------------------------------------

  ALTER TABLE "SCOTT"."COURSE" ADD FOREIGN KEY ("DEPT_NAME")
	  REFERENCES "SCOTT"."DEPARTMENT" ("NAME") ENABLE;
 
  ALTER TABLE "SCOTT"."COURSE" ADD FOREIGN KEY ("INS_ID")
	  REFERENCES "SCOTT"."INSTRUCTOR" ("ID") ENABLE;

--------------------------------------------------------
--  Ref Constraints for Table ELECT
--------------------------------------------------------

  ALTER TABLE "SCOTT"."ELECT" ADD FOREIGN KEY ("S_ID")
	  REFERENCES "SCOTT"."STUDENT" ("ID") ENABLE;
 
  ALTER TABLE "SCOTT"."ELECT" ADD FOREIGN KEY ("C_ID")
	  REFERENCES "SCOTT"."COURSE" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table INSTRUCTOR
--------------------------------------------------------

  ALTER TABLE "SCOTT"."INSTRUCTOR" ADD FOREIGN KEY ("ID")
	  REFERENCES "SCOTT"."ACCOUNT" ("USER_ID") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table LOG
--------------------------------------------------------

  ALTER TABLE "SCOTT"."LOG" ADD FOREIGN KEY ("CREATER")
	  REFERENCES "SCOTT"."COURSE" ("ID") ENABLE;
 
  ALTER TABLE "SCOTT"."LOG" ADD FOREIGN KEY ("RELATED")
	  REFERENCES "SCOTT"."STUDENT" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table STUDENT
--------------------------------------------------------

  ALTER TABLE "SCOTT"."STUDENT" ADD FOREIGN KEY ("DEPT_NAME")
	  REFERENCES "SCOTT"."DEPARTMENT" ("NAME") ENABLE;
 
  ALTER TABLE "SCOTT"."STUDENT" ADD FOREIGN KEY ("ID")
	  REFERENCES "SCOTT"."ACCOUNT" ("USER_ID") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRR_CRE_ADD
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "SCOTT"."TRR_CRE_ADD" AFTER
UPDATE OF "COMPLETED" ON "SCOTT"."ELECT" FOR EACH ROW begin     
 if :OLD.COMPLETED='N' and :NEW.COMPLETED='Y' then     
  update STUDENT set TOL_CRED = TOL_CRED+(select CREDITS from COURSE where ID=:OLD.C_ID) where ID=:OLD.S_ID;    
 end if;    
end; 
/
ALTER TRIGGER "SCOTT"."TRR_CRE_ADD" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRR_C_ID
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "SCOTT"."TRR_C_ID" BEFORE
INSERT ON "SCOTT"."COURSE" FOR EACH ROW BEGIN 
SELECT 'C'||SEQ_I_ID.NEXTVAL into :new.ID from dual; 
END;
/
ALTER TRIGGER "SCOTT"."TRR_C_ID" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRR_I_ID
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "SCOTT"."TRR_I_ID" BEFORE
INSERT ON "SCOTT"."INSTRUCTOR" REFERENCING OLD AS OLD NEW AS NEW FOR EACH ROW BEGIN   
SELECT 'I'||SEQ_I_ID.NEXTVAL into :new.ID from dual; 
INSERT INTO "ACCOUNT" (USER_ID, PASSWORD, IDENTITY) VALUES (:new.ID,'123','I');    
END;
/
ALTER TRIGGER "SCOTT"."TRR_I_ID" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRR_S_ID
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "SCOTT"."TRR_S_ID" BEFORE
INSERT ON "SCOTT"."STUDENT" REFERENCING OLD AS OLD NEW AS NEW FOR EACH ROW BEGIN   
SELECT 'S'||SEQ_S_ID.NEXTVAL INTO :new.ID FROM dual;   
INSERT INTO "ACCOUNT" (USER_ID, PASSWORD, IDENTITY) VALUES (:new.ID,'123','S');   
  
END;
/
ALTER TRIGGER "SCOTT"."TRR_S_ID" ENABLE;
--------------------------------------------------------
--  DDL for View ALL_COURSE
--------------------------------------------------------

  CREATE OR REPLACE VIEW "SCOTT"."ALL_COURSE" ("ID", "TITLE", "NAME", "DEPT_NAME", "HOURS", "CREDITS") AS 
  select COURSE.ID,COURSE.TITLE,INSTRUCTOR.NAME,COURSE.DEPT_NAME,COURSE.HOURS,COURSE.CREDITS
from COURSE,INSTRUCTOR
where COURSE.INS_ID = INSTRUCTOR.ID WITH CHECK OPTION ;
--------------------------------------------------------
--  DDL for View COURSE_STUDENT
--------------------------------------------------------

  CREATE OR REPLACE VIEW "SCOTT"."COURSE_STUDENT" ("S_ID", "ID", "TITLE", "NAME", "DEPT_NAME", "HOURS", "CREDITS", "COMPLETED") AS 
  select ELECT.S_ID,COURSE.ID,COURSE.TITLE,INSTRUCTOR.NAME,COURSE.DEPT_NAME,COURSE.HOURS,COURSE.CREDITS,ELECT.COMPLETED from COURSE,ELECT,INSTRUCTOR where COURSE.ID = ELECT.C_ID AND COURSE.INS_ID = INSTRUCTOR.ID ;
--------------------------------------------------------
--  DDL for View STUDENT_COURSE
--------------------------------------------------------

  CREATE OR REPLACE VIEW "SCOTT"."STUDENT_COURSE" ("C_ID", "COMPLETED", "ID", "NAME", "SEX", "DEPT_NAME", "TOL_CRED") AS 
  select ELECT.C_ID,ELECT.COMPLETED,STUDENT.ID,STUDENT.NAME,STUDENT.SEX,STUDENT.DEPT_NAME,STUDENT.TOL_CRED from ELECT,STUDENT where ELECT.S_ID = STUDENT.ID ;
